Add support to download draft releases via private github endpoint using device-os-flash-util
particle-iot/device-os-flash-util pull request #4
Opened 2021-08-19 02:33 UTC by keeramis

### Story
https://app.clubhouse.io/particle/story/83987

### Description
One of the steps of device-os release process automation (ota-tester script) is OTA updates. For OTA updates to work, a draft release needs to be downloaded by the ota-tester script to use with it's BinaryFlasher app. OTA-tester script uses the device-os-flash-util tool to download binaries but currently it doesn't support downloading the draft releases as draft releases are only accessible via the private github endpoint, and the API calls to access draft releases is slightly different with octokit. This PR adds support to download draft releases using the existing _downloadReleaseBinaries method.

### Run tests
```
keerthyamisagadda@MacBook-Pro device-os-flash-util (ch83987/start-a-minimal-unit-test-suite) $ GITHUB_TOKEN="REDACTED" npm run integration:test

> @particle/device-os-flash-util@0.5.1 integration:test /Users/keerthyamisagadda/code/device-os-flash-util
> nyc mocha --forbid-only "integration-tests/**/*.test.js" --timeout 30000

  ModuleCache can download a pre-determined draft release from GitHub using a GITHUB_TOKEN
Found cached module binaries
    ✔ can download a mock 1.9.0-rc.1
Found cached module binaries
    ✔ can download a production 2.1.0 release (47ms)
Downloading release binaries
Check for draft releases by hitting the (private) draft release API endpoint which requires GITHUB_TOKEN
    ✔ will error if tried with an unknown release (2658ms)

  3 passing (3s)
```

2021-08-19 02:36 UTC, keeramis commented
@joegoggins I created this new one as I was unable to add you in the [older PR](https://github.com/particle-iot/device-os-flash-util/pull/3). thanks!

2021-08-19 17:33 UTC, joegoggins approved these changes
This looks great to me, nice work @keeramis and @avtolstoy !

I'd be be in favor of merging it, cutting an npm release, and continuing on the path to using these new capabilities in the ota-tester npm module.

@sergeuz , given this is the first time this repo has received commits from other folks, could you take point on decision of what needs to be done to merge this and cutting a release?

On a different note, now that this tool as one unit test, I'd like to get this wired up in CI. I enqueued [this story](https://app.clubhouse.io/particle/story/85426/setup-ci-for-device-os-flash-util) with Sergey and I as owners. My plan is to tackle it next time we're actively doing dev on that repo so haven't assigned a sprint to it (and because it's not urgent).

2021-08-24 12:03 UTC, sergeuz requested changes
Nice job and thank you for adding tests! Some of the changes that I requested, such as preventing draft releases from being cached, may require refactoring of the existing code. Let me know if you would prefer me to tackle it.

2021-08-24 12:03 UTC, sergeuz commented on lib/module.js
> +const { release } = require('os');
Unused import.

2021-08-24 12:03 UTC, sergeuz commented on lib/module.js
> +		}
The output of `listReleases()` is paginated according to another instance where that API is [used](https://github.com/particle-iot/device-os-flash-util/blob/d5941bcc15565181458dae81f386d6a947d05a47/lib/module.js#L386-L409) in this module.

2021-08-24 12:03 UTC, sergeuz commented on lib/module.js
> +					throw err;
From the UX perspective, I would prefer if there was a command line flag (e.g. `--draft`) that would explicitly enable fetching of draft releases as they're potentially unstable. For the same reason, we should not be caching draft releases in the local filesystem which is what `ModuleCache` does for all downloaded releases now.

2021-08-24 12:03 UTC, sergeuz commented on lib/module.js
> +			});
Why is this necessary? The array of assets seems to be immediately available in the response returned by `_checkForDraftRelease()`, so both draft and non-draft releases can be actually handled in the same way here.

2021-08-24 12:03 UTC, sergeuz commented on lib/module.js
> +				if (draftRel == null) {
Let's either use the strict equality operator here (`===`) or simply check for truthiness of the returned object: `if (!draftRel) { ... }`.

2021-08-24 12:03 UTC, sergeuz commented on lib/module.js
> +		console.log("Check for draft releases by hitting the (private) draft release API endpoint which requires GITHUB_TOKEN");
The logger instance that is passed to the `ModuleCache`'s constructor should be used instead of `console.log()`. Same [here](https://github.com/particle-iot/device-os-flash-util/pull/4/files#diff-cdd77182e73349d6c83fbbce1cccf6f15972fbece4dbd9c52eececf1ca3bfcd5R241) and [here](https://github.com/particle-iot/device-os-flash-util/pull/4/files#diff-cdd77182e73349d6c83fbbce1cccf6f15972fbece4dbd9c52eececf1ca3bfcd5R244).

Also, this message is unnecessarily verbose. It would be better to fail early if a draft release is requested but the API access token is not specified (see my other comment about the `--draft` argument).

2021-08-24 12:03 UTC, sergeuz commented on lib/module.js
> +		//console.log(listAllReleases.data);
Let's remove these commented out log statements if they're no longer necessary.

2021-08-24 12:03 UTC, sergeuz commented on lib/module.js
> +			if (rel.tag_name == String('v' + version)) {
It's better to use the strict equality operator `===` instead of `==` everywhere in the code. Also, `version` is already a string (as well as the result of the concatenation), there's no need to construct a string object explicitly.

2021-08-24 12:03 UTC, sergeuz commented on lib/module.js
> +				if (rel.draft == true) {
Nit: `if (rel.draft) { ... }`.

2021-08-24 20:53 UTC, keeramis commented on lib/module.js
> +			});
@sergeuz When I tested it, it looks like the result from directly accessing the oktokit's `repos.listReleaseAssets` is not exactly the same as `repos.getReleaseByTag.assets.map(a => ({` [(this)](https://github.com/particle-iot/device-os-flash-util/blob/0690061e499ed14f1f7ad3314e2f1c8563edda85/lib/module.js#L290) which is why I used that approach. Might I be missing something here(?)

2021-08-24 20:55 UTC, keeramis commented
thanks for the review @sergeuz! I made some changes as you suggested related to logging and syntax. If you can check the  draft parts, that's absolutely fine by me. I will watch the magic happen. ✨

2021-08-26 19:20 UTC, sergeuz commented
I updated the PR so that it is now required to provide a `--draft` argument in the command line in order to download a draft release. Draft releases are no longer cached in the local filesystem.

2021-08-26 19:21 UTC, sergeuz approved these changes

2021-08-26 20:16 UTC, joegoggins approved these changes
Looks good @sergeuz , thanks.

One thing I wanted to call out is that this change will require @keeramis 's [ota-tester](https://github.com/particle-iot/pqa/pull/18/files) code to change:

Specifically, I believe 

`await moduleCache.getReleaseModules(version);` 

will become 

`await moduleCache.getReleaseModules(version, {noDraft: false});`


Sergey, if you could give that other PR a look and let Keerthy know if you have any other recommendations, that could also be useful. More broadly speaking, I feel that this `ota-tester` tool should be co-owned by Keerthy's team, your team, and my team until it's mature. If you want to collaborate to drive the vision of that tool, would definitely support that.

2021-08-27 08:21 UTC, sergeuz commented
@joegoggins Ah, I didn't know that the OTA tester uses `ModuleCache` directly. I'll change the `noDraft` parameter to `draft` then, as having to use a double negation is annoying in what is now a public interface.

2021-08-27 09:05 UTC, merged